Rework
tentaclenotsoft/website pull request #2
Opened 2021-07-12 07:11 UTC by ruj

2021-07-12 12:17 UTC, samueldurantes approved these changes

2021-07-14 20:49 UTC, samueldurantes approved these changes

2021-07-15 05:15 UTC, ruj commented on src/pages/index.tsx
> +                  <span className="">{repository.language}</span>
Change language text to a more discreet font

2021-07-15 05:20 UTC, samueldurantes requested changes
Change language text to a more discreet font

https://github.com/tentaclenotsoft/website/blob/024703e67d64234dc8e7806fa80c38087315df4e/src/pages/index.tsx#L50

2021-07-15 16:48 UTC, samueldurantes approved these changes

2021-07-15 19:45 UTC, samueldurantes approved these changes

2021-07-15 19:49 UTC, merged